var APP_DICT = {
	articleType:[
	    {value:"1",msg:"官方新闻"}
	    ,{value:"2",msg:"官方公告"}
	    ,{value:"3",msg:"精彩视频"}
	    ,{value:"4",msg:"精彩图片"}
	]
	,matchResult:[
	    {value:"1",msg:"胜"}
	    ,{value:"0",msg:"败"}
	    ,{value:"2",msg:"平"}
	]
	,isLocal:[
	    {value:"1",msg:"主场"}
	    ,{value:"0",msg:"客场"}
	]
	,yesOrNo:[
		{value:"0",msg:"否"}
	    ,{value:"1",msg:"是"}
	]
}
